# Creates all 1 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# GCPScrtMgr — Not used
# ---------------------------------------------------------------------------
New-StoreType "GCPScrtMgr" @'
{
  "Name": "GCPScrtMgr",
  "ShortName": "GCPScrtMgr",
  "Capability": "GCPScrtMgr",
  "ServerRequired": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": true,
    "Style": "Default",
    "StorePassword": {
      "Description": "Password used to encrypt the private key of ALL certificate secrets.  Please see [Certificate Encryption Details](#certificate-encryption-details) for more information",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "PasswordSecretSuffix",
      "DisplayName": "Password Secret Location Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "IncludeChain",
      "DisplayName": "Include Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "True",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "ReplicationRegions",
      "DisplayName": "Replication Regions",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "TtlDuration",
      "DisplayName": "TTL Duration",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "VersionDestroyTtlDuration",
      "DisplayName": "Version Destroy TTL Duration",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "tags",
      "DisplayName": "Tags",
      "Type": "String",
      "Description": "An optional list of one-to-many comma delimited Organization level tag Key:Value combinations.  Values should be entered as tagKey1:tagVal1,tagKey2:tagVal2,...tagKeyN:tagValN",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "labels",
      "DisplayName": "Labels",
      "Type": "String",
      "Description": "An optional list of one-to-many comma delimited label key:value pairs to assign to the secret.  Values should be entered as key1:value1,key2:value2,...,keyN:valueN.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "ttlDuration",
      "DisplayName": "TTL Duration",
      "Type": "String",
      "Description": "An optional number of days to provide after which a secret will be deleted.  If not provided, secret will stay around until explicitly deleted.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "versionDestroyTtlDuration",
      "DisplayName": "Version Destroy TTL Duration",
      "Type": "String",
      "Description": "An optional number of days to provide after a secret is destroyed that its versions will stay around.  If not provided, versions will be permanently destroyed when the secret is destroyed.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    }
  ],
  "StorePathDescription": "The Project ID of the Google Secret Manager being managed."
}
'@


Write-Host "Completed."
