#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: GCPScrtMgr"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "GCPScrtMgr",
  "ShortName": "GCPScrtMgr",
  "Capability": "GCPScrtMgr",
  "ServerRequired": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": true,
    "Style": "Default",
    "StorePassword": {
      "Description": "Password used to encrypt the private key of ALL certificate secrets.  Please see [Certificate Encryption Details](#certificate-encryption-details) for more information",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "PasswordSecretSuffix",
      "DisplayName": "Password Secret Location Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "If storing a certificate with an encrypted private key, this is the suffix to add to the certificate (secret) alias name where the encrypted private key password will be stored.  Please see [Certificate Encryption Details](#certificate-encryption-details) for more information"
    },
    {
      "Name": "IncludeChain",
      "DisplayName": "Include Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "True",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "Determines whether to include the certificate chain when adding a certificate as a secret."
    }
  ],
  "EntryParameters": [
    {
      "Name": "tags",
      "DisplayName": "Tags",
      "Type": "String",
      "Description": "An optional list of one-to-many comma delimited Organization level tag Key:Value combinations.  Values should be entered as tagKey1:tagVal1,tagKey2:tagVal2,...tagKeyN:tagValN",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "labels",
      "DisplayName": "Labels",
      "Type": "String",
      "Description": "An optional list of one-to-many comma delimited label key:value pairs to assign to the secret.  Values should be entered as key1:value1,key2:value2,...,keyN:valueN.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "replicationRegions",
      "DisplayName": "Replication Regions",
      "Type": "String",
      "Description": "An optional list of valid comma delimited GCP regions to replicate secrets to (user managed replication).  If left blank, GCP default behavior (automatic replication) will be executed.  Values can also be entered as region1:path1,region2:path2,...,regionN:pathN if providing a kmsKeyName path for each region is desired.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "ttlDuration",
      "DisplayName": "TTL Duration",
      "Type": "String",
      "Description": "An optional number of days to provide after which a secret will be deleted.  If not provided, secret will stay around until explicitly deleted.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "versionDestroyTtlDuration",
      "DisplayName": "Version Destroy TTL Duration",
      "Type": "String",
      "Description": "An optional number of days to provide after a secret is destroyed that its versions will stay around.  If not provided, versions will be permanently destroyed when the secret is destroyed.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    }
  ]
}'

